### ISSUE TITLE
03 View friend - Basic UI

### ISSUE THREAD

**Issue by FabianEgartner** [Friendary-Org/Friendary-App#10]
- [x] Profile Picture placeholder at the top (Big, able to hold pictures for functionality later)
- [x] Star Button in the top right corner
- [x] Name Text box
- [x] Little note button for a short description
- [x] Scrollable List in which we can place boxes
- [x] Box with date in it
- [x] Box with a Header (Category name) and multiple possible entries (Category entries)
- [x] Edit Button with a pencil as Symbol
- [x] Cancel BUtton (Functionality of a return button later)

**Comment by JesterJesterson** [comment]
https://media.discordapp.net/attachments/1014145874802266203/1020005501444038728/11_View_Friend_Screen.jpg?width=518&height=669
^Like this
