### ISSUE TITLE
06 Edit/Delete Friend - Basic UI

### ISSUE THREAD

**Issue by FabianEgartner** [Friendary-Org/Friendary-App#13]
- [x] Favourite Star in the upper right corner of screen
- [x] Profile picture placeholer with button to change it (Might be the same component)
- [x] Note button for short description
- [x] Textbox for Name
- [x] List with entry boxes
- [x] Entry box with Date and "Birthday" text 
- [x] Entry box with Category name, entry text fields, and category symbol besides name
- [x] Multiple other entry boxes in the list for demonstration if possible
- [x] Delete friend button
- [x] Add category button
- [x] Cancel/Back button

**Comment by JesterJesterson** [comment]
https://media.discordapp.net/attachments/1014145874802266203/1020005501725061135/12_Edit_Friend_Screen.jpg?width=518&height=669
^Like this
