### ISSUE TITLE
02 Add Friend Screen - Basic UI

### ISSUE THREAD

**Issue by FabianEgartner** [Friendary-Org/Friendary-App#7]
- [x] Text at the Top saying "ADD FRIEND"
- [x] Profile picture (Placeholder, must be able to contain pictures if possible)
- [x] Name Box below the picture
- [x] Date Box below the Name Box
- [x] "Add category" button with a + besides it
- [x] "Save" Button
- [x] X Button to cancel

**Comment by JesterJesterson** [comment]
[](url)https://media.discordapp.net/attachments/1014145874802266203/1020005501121081477/10_Add_Friend_Screen.jpg?width=518&height=669 
^Like this
